workflows:
  cordova-ios-workflow:
    name: Build Cordova iOS
    max_build_duration: 45
    environment:
      vars:
        CORDOVA_PLATFORM: ios
      node: 16.20.0
      xcode: latest
    scripts:
      - name: Install Cordova
        script: npm install -g cordova
      - name: Install project dependencies
        script: npm install
      - name: Add iOS platform
        script: |
          cordova platform rm ios || true
          cordova platform add ios
      - name: Build iOS
        script: cordova build ios --release
    artifacts:
      - platforms/ios/build/**/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
